//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileKeySearch.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_ANAL_WIZPAGE_FILE           107
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_APP_TYPE                    129
#define IDR_ACCELERATOR1                132
#define IDD_REPORTDLG                   136
#define IDD_KEYEXPORT_DLG               137
#define IDD_KEYIMPORT_DLG               138
#define IDD_MANAGER_DLG                 140
#define IDD_NEWKEYNAME_DLG              141
#define IDD_ANAL_WIZPAGE_KEYS           142
#define IDD_ANAL_WIZPAGE_ANAL           143
#define IDR_TB_APP                      144
#define IDD_KEYUPDATE_DLG               147
#define IDD_ANALYZE_DLG                 148
#define IDI_ICON_KEY_GOLD               149
#define IDI_ICON_KEY_GREY               150
#define IDI_ICON_LEAF_GREY              151
#define IDI_ICON_LEAF_RED               152
#define IDR_MENU_MEDIA                  153
#define IDB_MEDIA_EXTRACT               154
#define IDB_MEDIA_PREVIEW               155
#define IDB_MEDIA_REMOVE                157
#define IDD_NEWEXT_DLG                  159
#define IDI_ICON_KEY_RED                160
#define IDD_MEDIA_DLG                   161
#define IDB_MEDIA_PROPERTIES            163
#define IDD_MEDIA_EXTRACT_DLG           164
#define IDC_EDIT2                       1001
#define IDC_EDIT_MESSAGE                1001
#define IDC_EDIT_EXTENSIONS             1001
#define IDC_TXT_OFFSET                  1001
#define IDC_EDIT1                       1002
#define IDC_EDIT_LASTERROR              1002
#define IDC_EDIT_ABOUT_PRG              1002
#define IDC_EDIT_EVENTLOG               1002
#define IDC_EVENTLOG                    1002
#define IDC_EDIT_COMMENT                1002
#define IDC_EDIT_NEWNAME                1002
#define IDC_EDIT_FILENAME               1002
#define IDC_TXT_NAME                    1002
#define IDC_BTN_EXPORT                  1003
#define IDC_BTN_CLOSE                   1004
#define IDC_BTN_SAVETO                  1005
#define IDC_BTN_OPENFILE                1006
#define IDC_BTN_IMPORT                  1007
#define IDC_CMB_IMPORT_TYPE             1009
#define IDC_LIST_KEYNAMES               1010
#define IDC_BTN_APPLY                   1011
#define IDC_BTN_NEW_KEY                 1017
#define IDC_BTN_DELETE_KEY              1018
#define IDC_EDIT_CSO                    1020
#define IDC_RADIO_CSO_TYPE_CONTENT      1021
#define IDC_RADIO_CSO_TYPE_TOTAL        1022
#define IDC_EDIT_SKIP_SCOPE             1023
#define IDC_EDIT_SIGNATURE              1024
#define IDC_SPIN_CSO                    1028
#define IDC_BTN_OPEN                    1029
#define IDC_LIST_AVAILABLE              1031
#define IDC_LIST_SELECTED               1032
#define IDC_BTN_ADD                     1033
#define IDC_BTN_DEL                     1034
#define IDC_BTN_ADDALL                  1035
#define IDC_BTN_DELALL                  1036
#define IDC_CHECK_START_NOW             1037
#define IDC_LIST_KEYS                   1038
#define IDC_BTN_KEYMANAGER              1040
#define IDC_PROGRESS_TOTAL              1042
#define IDC_STATIC_FOUND                1043
#define IDC_BTN_PAUSE                   1044
#define IDC_CMB_PRIORITY                1045
#define IDC_CMB_MEMORY                  1045
#define IDC_STATIC_REMAINS              1046
#define IDC_CMB_EXT                     1047
#define IDC_STATIC_SPEED                1048
#define IDC_STATIC_STATISTICS           1049
#define IDC_SPIN_SKIP_SCOPE             1050
#define IDC_TXT_KEYLIST_TITLE           1052
#define IDC_SPIN_OFFSET                 1053
#define IDC_TXT_SIZE                    1054
#define IDC_SPIN_SIZE                   1055
#define IDC_CHECK_END                   1056
#define IDC_BTN_TERMINATE               1058
#define IDC_TXT_PROGRESS                1060
#define IDC_PROGRESS_BAR                1061
#define IDC_BUTTON1                     1062
#define ID_SIGNATURE_NEW                32771
#define ID_MANAGEKEYS                   32775
#define ID_KEYS_IMPORT                  32778
#define ID_KEYS_EXPORT                  32779
#define ID_KEYS_ANAL                    32787
#define ID_EXTRACT_START                32790
#define ID_ANALYZE_START                32792
#define ID_MEDIA_RUN                    32800
#define ID_MEDIA_EXTRACT                32801
#define ID_MEDIA_RENAME                 32802
#define ID_MEDIA_REMOVE                 32804
#define ID_MEDIA_OPEN                   32805
#define ID_MEDIA_SET_EXTENSION          32807
#define ID_BUTTON32808                  32808
#define ID_MEDIA_PROPERTIES             32809
#define ID_Menu                         32810
#define ID_1_COPYOFFSET                 32811
#define ID_1_COPYSIZE                   32812
#define ID_MEDIA_COPY_NAME              32813
#define ID_MEDIA_COPY_OFFSET            32814
#define ID_MEDIA_COPY_SIZE              32815
#define ID_1_VIEW                       32816
#define ID_MEDIA_VIEW                   32817
#define ID_MEDIA_OPENEXTRACTFOLDER      32818
#define ID_WINDOW                       32819
#define ID_WINDOW_E                     32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        165
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1063
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
